### PR TITLE
Add support for 'simnet' network

### LINKED ISSUE #184: "Unknown link format" on simnet with lnd + btcd
**Describe the bug**
I'm running a local simnet network with btcd and lnd. I managed to connect Zap iOS to it by running `lndconnect` and changing IP to `192.168.0.1` (my phone and laptop are in the same local network). Everything works, History gets updates properly, but sending doesn't work. I use `lncli addinvoice` to generate new invoices, they appear in History, but when I paste address or scan QR code (I use https://www.the-qrcode-generator.com to convert payment requests to QR codes) I get "Unknown link format" error. Paying with `lncli payinvoice` works.
I also tried prepending 'lightning:', it didn't help. And I tried multi-node setup, where one node generates an invoice and the other tries to pay.

**To Reproduce**
1. Run a simnet network with `btcd`.
2. Run `lnd`, create a wallet with `lncli create`.
3. Run `lndconnect` and get Zap link, change IP address to you laptop's one.
4. Paste the link to Zap iOS, mine a few blocks and see the main screen.
5. Run `lncli addinvoice --amt=10`. Get a payment request and paste it into Zap iOS.
6. See "Unknown link format" error.
7. Generate QR code for the payment request and scan it in Zap iOS, get the same error.

Here's payment request I use:
```
lnsb130n1pwjsleupp5myrnmrgts0nehmk980e4s5l2s3ega7daw0k04k26x89v9u42077qdqqcqzpgd04gakvmly5y0z0xt6ftxprgx6ldnc4z89mwh08hsz03pee29uyknqfwqv8plgg2m7974l5yrrsdlan3tztyphekp9afpz3nfchzwtqpe53l6u
```
It was created by `lncli addinvoice --amt=13`.

**Expected behavior**
QR code or address are parsed correctly and I can send a payment.

**Your environment**
- Device: iPhone6
- OS: iOS 12.3
- Version: zap version 0.3.0, build 37, lnd version: 0.7.0 g93aad8

- btcd version 0.12.0-beta
- lnd version 0.7.0-beta commit=v0.7.0-beta-44-g93aad89f4c132089d77181a7aec5d717bf1c621a

### PR DESCRIPTION
**Pull request by Jeiwan**
Fixes https://github.com/LN-Zap/zap-iOS/issues/184

### CODE REVIEW

**Comment by Jeiwan** [comment]
Tests pass but something is wrong with 'pod_lib_lint' step. It also failed on previous builds.

**Comment by Jeiwan** [comment]
Alright, I fixed it. 🙂

**Comment by ottosuess** [comment]
awesome, thank you.

when running the tests from xcode i get an error: `error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

can be fixed by running pod install in the `Example` folder

**Comment by Jeiwan** [comment]
@ottosuess Could you please close this PR? It was merged but is still hanging in my PR list.

**Comment by ottosuess** [comment]
isn't `merged == closed`? idk if i can close it even more. 😅

**Comment by Jeiwan** [comment]
It's gone now! Thanks for whatever you did or didn't. 😉

**Pull request merged**
